name: Continuous Delivery

on:
  push:
    branches:
      - main

  workflow_dispatch:

concurrency:
  group: cd-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  release:
    name: Release Versioning
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v4
        with:
          config-file: release-please.config.json
          manifest-file: release-please.manifest.json

    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
