name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ci-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ci-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

  lint:
    name: Code Linting
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Restore Dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ci-${{ hashFiles('./package-lock.json') }}

      - name: Code Linting
        run: npm run lint

  test:
    name: Code Testing
    needs: dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Restore Dependencies
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: ci-${{ hashFiles('./package-lock.json') }}

      - name: Code Testing
        run: npm run test
