name: PR Lint

on:
  pull_request:
    types:
      - assigned
      - unassigned
      - opened
      - edited
      - synchronize
      - reopened
      - labeled
      - unlabeled
      - ready_for_review

  workflow_dispatch:

concurrency:
  group: pr-lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    name: PR Labeling
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Add labels
        uses: actions/labeler@v5
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true

  dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: pr-lint-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            pr-lint-

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

  linting:
    name: PR Linting
    needs: dependencies
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Restore Dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
          key: pr-lint-${{ hashFiles('./package-lock.json') }}

      - name: Dependencies Fallback
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Lint Commits
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Lint PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx danger ci -f
